# This is a basic workflow to help you get started with Actions

name: Build and Publish Docs


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  generate-docs:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          include-prerelease: true
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: path/to/your/docfx.json

      # Publish generated site using GitHub Pages
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: _site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
